services:
  - type: web
    name: edutaai-whatsapp-service
    runtime: image
    image:
      url: evoapicloud/evolution-api:latest
    plan: free
    region: singapore
    envVars:
      - key: SERVER_PORT
        value: "8080"
      - key: SERVER_TYPE
        value: http

      # Render auto-prompt rokne ke liye
      - key: SERVER_URL
        value: "http://localhost:8080"

      # Authentication (Sabhi users ke liye same password)
      - key: AUTHENTICATION_TYPE
        value: apikey
      - key: AUTHENTICATION_API_KEY
        value: "Mykey123"

      # Database Completely Disabled (Ye error fix karega)
      - key: DATABASE_ENABLED
        value: "false"

      # Storage completely disabled (RAM bachane ke liye)
      - key: STORE_MESSAGES
        value: "false"
      - key: STORE_MESSAGE_UPDATING
        value: "false"
      - key: STORE_CHATS
        value: "false"
      - key: STORE_CONTACTS
        value: "false"

      # Panel UI Customization
      - key: DEL_INSTANCE
        value: "false"
      - key: CONFIG_SESSION_PHONE_CLIENT
        value: "EdutaAI WhatsApp Gateway"
      - key: CONFIG_VIEW_MANAGER_TITLE
        value: "EdutaAI - WhatsApp Gateway"
      - key: CONFIG_VIEW_MANAGER_COLOR
        value: "#075e54"
