services:
  - type: web
    name: edutaai-whatsapp-gateway
    runtime: image
    image:
      url: devlikeapro/waha:latest
    plan: free
    region: singapore
    envVars:
      - key: PORT
        value: "8080"
      - key: WAHA_HTTP_PORT
        value: "8080"

      # Lightweight engine (बिना क्रैश हुए चलने के लिए)
      - key: WHATSAPP_DEFAULT_ENGINE
        value: "NOWEB"

      # API Security (वेबसाइट से मैसेज भेजने के लिए)
      - key: WAHA_API_KEY
        value: "Mykey123"

      # Dashboard Security (लॉगिन पॉपअप को खोलने के लिए सटीक डिटेल्स)
      - key: WAHA_DASHBOARD_USERNAME
        value: "admin"
      - key: WAHA_DASHBOARD_PASSWORD
        value: "Mykey123"
