services:
  - type: web
    name: edutaai-whatsapp-gateway
    runtime: image
    image:
      url: devlikeapro/waha:latest
    plan: free
    region: singapore
    envVars:
      - key: PORT
        value: "8080"
      - key: WAHA_HTTP_PORT
        value: "8080"

      # Authentication (Aapki aur users ki security ke liye)
      - key: WAHA_API_KEY
        value: "Mykey123"

      # Sabse zaroori: Lightweight engine (Bina heavy browser ke)
      - key: WHATSAPP_DEFAULT_ENGINE
        value: "NOWEB"
